version: '2'

services:
  db:
    image: postgres:9.6
    env_file:
      - ./conf/start/docker/postgres.env
    networks:
      default:
        aliases:
          - postgres
  rabbitmq:
  elastic:
    image: elasticsearch:5
    networks:
      default:
        aliases:
          - elasticsearch
  rabbitmq:
    image: rabbitmq:3
  promsrv:
    build: ./conf/start/docker/prometheus/
    volumes:
      - prometheus_sd:/prometheus_sd
  nginx:
    image: nginx:mainline-alpine
    ports:
      - "443:443"
    depends_on:
      - promsrv
      - web
    volumes:
      - ./conf/start/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./conf/start/docker/tls:/etc/nginx/tls
  web:
    extends:
      file: docker-compose.common.yml
      service: app
    command: runserver
    depends_on:
      - db
      - elastic
      - rabbitmq
  workers:
    extends:
      file: docker-compose.common.yml
      service: app
    command: runworkers --external-hostname workers --prometheus-sd-file /prometheus_sd/workers.yml
    depends_on:
      - db
      - elastic
      - rabbitmq
    volumes:
      - prometheus_sd:/prometheus_sd

networks:
  default:

volumes:
  prometheus_sd:
